events {}

http {
    # This is the "Phone Directory"
    upstream my_app {
        # Docker's internal DNS lets us use the service names from docker-compose
        server app-blue:80;
        server app-green:80;
    }

    server {
        listen 80;

        location / {
            # This tells Nginx to send all traffic to the Upstream group
            proxy_pass http://my_app;
            
            # These lines make sure the app knows the user's real IP address
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}